# Generated by Django 3.2 on 2021-07-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article2articletag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(through='blog.Article2ArticleTag', to='blog.ArticleTag', verbose_name='文章标签'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='site_theme',
            field=models.CharField(max_length=64, null=True, verbose_name='站点主题'),
        ),
    ]
