# Generated by Django 3.2 on 2021-07-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210710_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='site_theme',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='站点主题'),
        ),
    ]
