# Generated by Django 3.2 on 2021-07-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdetail',
            options={'verbose_name_plural': '每日阅读量表'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name_plural': '文章阅读量表'},
        ),
    ]
