# Generated by Django 3.2 on 2021-07-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0002_auto_20210705_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='readdetail',
            name='user',
            field=models.CharField(default='guoxu', max_length=15, verbose_name='作者'),
        ),
    ]
