# Generated by Django 3.2 on 2021-07-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0003_readdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='user',
            field=models.CharField(max_length=15, verbose_name='作者'),
        ),
    ]
