# Generated by Django 3.2 on 2021-07-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=15, null=True, verbose_name='昵称'),
        ),
    ]
