# Generated by Django 3.2 on 2021-07-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_comment_root'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_time'], 'verbose_name_plural': '评论表'},
        ),
    ]
