# Generated by Django 3.2 on 2021-07-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecount',
            old_name='Up_num',
            new_name='up_num',
        ),
    ]
